// Code generated by goctl. DO NOT EDIT.
package types

type HealthResp struct {
	Message string `json:"message"`
}

type PostUserReq struct {
	Email    string `json:"email"`    // 用户邮箱
	Phone    string `json:"phone"`    // 用户手机
	Password string `json:"password"` // 用户密码
	Nickname string `json:"nickname"` // 用户昵称
	Gender   int64  `json:"gender"`   // 0:未公开 1:女 2:男
	Avatar   string `json:"avatar"`   // 用户头像
	Role     int64  `json:"role"`     // 0:用户 1:管理员
}

type PostUserResp struct {
	Id        int64  `json:"id"`        // primary key
	Email     string `json:"email"`     // 用户邮箱
	Phone     string `json:"phone"`     // 用户手机
	Password  string `json:"password"`  // 用户密码
	Nickname  string `json:"nickname"`  // 用户昵称
	Gender    int64  `json:"gender"`    // 0:未公开 1:女 2:男
	Avatar    string `json:"avatar"`    // 用户头像
	Role      int64  `json:"role"`      // 0:用户 1:管理员
	CreatedAt string `json:"createdAt"` // 创建时间
	UpdatedAt string `json:"updatedAt"` // 更新时间
}

type DeleteUserReq struct {
	Id int64 `json:"id"`
}

type DeleteUserResp struct {
	Status bool `json:"status"` // 是否删除成功
}

type PutUserReq struct {
	Id       int64  `json:"id"`
	Email    string `json:"email"`    // 用户邮箱
	Phone    string `json:"phone"`    // 用户手机
	Password string `json:"password"` // 用户密码
	Nickname string `json:"nickname"` // 用户昵称
	Gender   int64  `json:"gender"`   // 0:未公开 1:女 2:男
	Avatar   string `json:"avatar"`   // 用户头像
	Role     int64  `json:"role"`     // 0:用户 1:管理员
}

type PutUserResp struct {
	Id        int64  `json:"id"`        // primary key
	Email     string `json:"email"`     // 用户邮箱
	Phone     string `json:"phone"`     // 用户手机
	Password  string `json:"password"`  // 用户密码
	Nickname  string `json:"nickname"`  // 用户昵称
	Gender    int64  `json:"gender"`    // 0:未公开 1:女 2:男
	Avatar    string `json:"avatar"`    // 用户头像
	Role      int64  `json:"role"`      // 0:用户 1:管理员
	CreatedAt string `json:"createdAt"` // 创建时间
	UpdatedAt string `json:"updatedAt"` // 更新时间
}

type GetUserReq struct {
	Id int64 `form:"id"`
}

type GetUserResp struct {
	Id        int64  `json:"id"`        // primary key
	Email     string `json:"email"`     // 用户邮箱
	Phone     string `json:"phone"`     // 用户手机
	Password  string `json:"password"`  // 用户密码
	Nickname  string `json:"nickname"`  // 用户昵称
	Gender    int64  `json:"gender"`    // 0:未公开 1:女 2:男
	Avatar    string `json:"avatar"`    // 用户头像
	Role      int64  `json:"role"`      // 0:用户 1:管理员
	CreatedAt string `json:"createdAt"` // 创建时间
	UpdatedAt string `json:"updatedAt"` // 更新时间
}
