CREATE TABLE IF NOT EXISTS `type` (
  `code` VARCHAR(255) NOT NULL COMMENT 'primary key',
  `name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '类型',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` DATETIME DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`code`),
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '文章类型表';